#!/bin/bash

export DJANGO_SETTINGS_MODULE=project.settings

if [ `pwd | grep ^/home/nhoyt/src` ]; then
    export PYTHONPATH=/usr/local/src:/home/nhoyt/src
elif [ `pwd | grep ^/usr/local/faetest` ]; then
    export PYTHONPATH=/usr/local/src:/usr/local/faetest
elif [ `pwd | grep ^/usr/local/faedata` ]; then
    export PYTHONPATH=/usr/local/src:/usr/local/faedata
fi

if [ -n $1 ]; then
    eval /usr/local/bin/python2.5 $1
fi
