#!/bin/bash

export DJANGO_SETTINGS_MODULE=project.settings

if [ `pwd | grep ^/home/nhoyt/src` ]; then
    export PYTHONPATH=/services/faedev/lib:/home/nhoyt/src
elif [ `pwd | grep ^/services/faetest/lib` ]; then
    export PYTHONPATH=/services/faetest/lib
elif [ `pwd | grep ^/services/faedata/lib` ]; then
    export PYTHONPATH=/services/faedata/lib
fi

# Check for command-line argument.
if [ -z $1 ]; then
    echo 'Please specify a filename.'
    exit 0
fi

# If file exists then run it as a python script,
# passing in any additional arguments.
if [ -e $1 ]; then
    python $@
else echo 'Please specify an existing file to run.'
fi
