#!/bin/bash

export DJANGO_SETTINGS_MODULE=project.settings

if [ `pwd | grep ^/home/nhoyt/src` ]; then
    export PYTHONPATH=/services/faedev/lib:/home/nhoyt/src
elif [ `pwd | grep ^/services/faetest/lib` ]; then
    export PYTHONPATH=/services/faetest/lib
elif [ `pwd | grep ^/services/faedata/lib` ]; then
    export PYTHONPATH=/services/faedata/lib
fi

if [ -n $1 ]; then
    eval /usr/local/bin/python2.5 $1
fi
